SCRIPTURE_META = begin
  [{"number"=>1,
    "abbr"=>"GEN",
    "name"=>"Genesis",
    "string_id"=>"genesis",
    "chapters"=>
    [{"number"=>1, "verses"=>31},
      {"number"=>2, "verses"=>25},
      {"number"=>3, "verses"=>24},
      {"number"=>4, "verses"=>26},
      {"number"=>5, "verses"=>32},
      {"number"=>6, "verses"=>22},
      {"number"=>7, "verses"=>24},
      {"number"=>8, "verses"=>22},
      {"number"=>9, "verses"=>29},
      {"number"=>10, "verses"=>32},
      {"number"=>11, "verses"=>32},
      {"number"=>12, "verses"=>20},
      {"number"=>13, "verses"=>18},
      {"number"=>14, "verses"=>24},
      {"number"=>15, "verses"=>21},
      {"number"=>16, "verses"=>16},
      {"number"=>17, "verses"=>27},
      {"number"=>18, "verses"=>33},
      {"number"=>19, "verses"=>38},
      {"number"=>20, "verses"=>18},
      {"number"=>21, "verses"=>34},
      {"number"=>22, "verses"=>24},
      {"number"=>23, "verses"=>20},
      {"number"=>24, "verses"=>67},
      {"number"=>25, "verses"=>34},
      {"number"=>26, "verses"=>35},
      {"number"=>27, "verses"=>46},
      {"number"=>28, "verses"=>22},
      {"number"=>29, "verses"=>35},
      {"number"=>30, "verses"=>43},
      {"number"=>31, "verses"=>55},
      {"number"=>32, "verses"=>32},
      {"number"=>33, "verses"=>20},
      {"number"=>34, "verses"=>31},
      {"number"=>35, "verses"=>29},
      {"number"=>36, "verses"=>43},
      {"number"=>37, "verses"=>36},
      {"number"=>38, "verses"=>30},
      {"number"=>39, "verses"=>23},
      {"number"=>40, "verses"=>23},
      {"number"=>41, "verses"=>57},
      {"number"=>42, "verses"=>38},
      {"number"=>43, "verses"=>34},
      {"number"=>44, "verses"=>34},
      {"number"=>45, "verses"=>28},
      {"number"=>46, "verses"=>34},
      {"number"=>47, "verses"=>31},
      {"number"=>48, "verses"=>22},
      {"number"=>49, "verses"=>33},
      {"number"=>50, "verses"=>26}]},
  {"number"=>2,
    "abbr"=>"EXO",
    "name"=>"Exodus",
    "string_id"=>"exodus",
    "chapters"=>
    [{"number"=>1, "verses"=>22},
      {"number"=>2, "verses"=>25},
      {"number"=>3, "verses"=>22},
      {"number"=>4, "verses"=>31},
      {"number"=>5, "verses"=>23},
      {"number"=>6, "verses"=>30},
      {"number"=>7, "verses"=>25},
      {"number"=>8, "verses"=>32},
      {"number"=>9, "verses"=>35},
      {"number"=>10, "verses"=>29},
      {"number"=>11, "verses"=>10},
      {"number"=>12, "verses"=>51},
      {"number"=>13, "verses"=>22},
      {"number"=>14, "verses"=>31},
      {"number"=>15, "verses"=>27},
      {"number"=>16, "verses"=>36},
      {"number"=>17, "verses"=>16},
      {"number"=>18, "verses"=>27},
      {"number"=>19, "verses"=>25},
      {"number"=>20, "verses"=>26},
      {"number"=>21, "verses"=>36},
      {"number"=>22, "verses"=>31},
      {"number"=>23, "verses"=>33},
      {"number"=>24, "verses"=>18},
      {"number"=>25, "verses"=>40},
      {"number"=>26, "verses"=>37},
      {"number"=>27, "verses"=>21},
      {"number"=>28, "verses"=>43},
      {"number"=>29, "verses"=>46},
      {"number"=>30, "verses"=>38},
      {"number"=>31, "verses"=>18},
      {"number"=>32, "verses"=>35},
      {"number"=>33, "verses"=>23},
      {"number"=>34, "verses"=>35},
      {"number"=>35, "verses"=>35},
      {"number"=>36, "verses"=>38},
      {"number"=>37, "verses"=>29},
      {"number"=>38, "verses"=>31},
      {"number"=>39, "verses"=>43},
      {"number"=>40, "verses"=>38}]},
  {"number"=>3,
    "abbr"=>"LEV",
    "name"=>"Leviticus",
    "string_id"=>"leviticus",
    "chapters"=>
    [{"number"=>1, "verses"=>17},
      {"number"=>2, "verses"=>16},
      {"number"=>3, "verses"=>17},
      {"number"=>4, "verses"=>35},
      {"number"=>5, "verses"=>19},
      {"number"=>6, "verses"=>30},
      {"number"=>7, "verses"=>38},
      {"number"=>8, "verses"=>36},
      {"number"=>9, "verses"=>24},
      {"number"=>10, "verses"=>20},
      {"number"=>11, "verses"=>47},
      {"number"=>12, "verses"=>8},
      {"number"=>13, "verses"=>59},
      {"number"=>14, "verses"=>57},
      {"number"=>15, "verses"=>33},
      {"number"=>16, "verses"=>34},
      {"number"=>17, "verses"=>16},
      {"number"=>18, "verses"=>30},
      {"number"=>19, "verses"=>37},
      {"number"=>20, "verses"=>27},
      {"number"=>21, "verses"=>24},
      {"number"=>22, "verses"=>33},
      {"number"=>23, "verses"=>44},
      {"number"=>24, "verses"=>23},
      {"number"=>25, "verses"=>55},
      {"number"=>26, "verses"=>46},
      {"number"=>27, "verses"=>34}]},
  {"number"=>4,
    "abbr"=>"NUM",
    "name"=>"Numbers",
    "string_id"=>"numbers",
    "chapters"=>
    [{"number"=>1, "verses"=>54},
      {"number"=>2, "verses"=>34},
      {"number"=>3, "verses"=>51},
      {"number"=>4, "verses"=>49},
      {"number"=>5, "verses"=>31},
      {"number"=>6, "verses"=>27},
      {"number"=>7, "verses"=>89},
      {"number"=>8, "verses"=>26},
      {"number"=>9, "verses"=>23},
      {"number"=>10, "verses"=>36},
      {"number"=>11, "verses"=>35},
      {"number"=>12, "verses"=>16},
      {"number"=>13, "verses"=>33},
      {"number"=>14, "verses"=>45},
      {"number"=>15, "verses"=>41},
      {"number"=>16, "verses"=>50},
      {"number"=>17, "verses"=>13},
      {"number"=>18, "verses"=>32},
      {"number"=>19, "verses"=>22},
      {"number"=>20, "verses"=>29},
      {"number"=>21, "verses"=>35},
      {"number"=>22, "verses"=>41},
      {"number"=>23, "verses"=>30},
      {"number"=>24, "verses"=>25},
      {"number"=>25, "verses"=>18},
      {"number"=>26, "verses"=>65},
      {"number"=>27, "verses"=>23},
      {"number"=>28, "verses"=>31},
      {"number"=>29, "verses"=>40},
      {"number"=>30, "verses"=>16},
      {"number"=>31, "verses"=>54},
      {"number"=>32, "verses"=>42},
      {"number"=>33, "verses"=>56},
      {"number"=>34, "verses"=>29},
      {"number"=>35, "verses"=>34},
      {"number"=>36, "verses"=>13}]},
  {"number"=>5,
    "abbr"=>"DEU",
    "name"=>"Deuteronomy",
    "string_id"=>"deuteronomy",
    "chapters"=>
    [{"number"=>1, "verses"=>46},
      {"number"=>2, "verses"=>37},
      {"number"=>3, "verses"=>29},
      {"number"=>4, "verses"=>49},
      {"number"=>5, "verses"=>33},
      {"number"=>6, "verses"=>25},
      {"number"=>7, "verses"=>26},
      {"number"=>8, "verses"=>20},
      {"number"=>9, "verses"=>29},
      {"number"=>10, "verses"=>22},
      {"number"=>11, "verses"=>32},
      {"number"=>12, "verses"=>32},
      {"number"=>13, "verses"=>18},
      {"number"=>14, "verses"=>29},
      {"number"=>15, "verses"=>23},
      {"number"=>16, "verses"=>22},
      {"number"=>17, "verses"=>20},
      {"number"=>18, "verses"=>22},
      {"number"=>19, "verses"=>21},
      {"number"=>20, "verses"=>20},
      {"number"=>21, "verses"=>23},
      {"number"=>22, "verses"=>30},
      {"number"=>23, "verses"=>25},
      {"number"=>24, "verses"=>22},
      {"number"=>25, "verses"=>19},
      {"number"=>26, "verses"=>19},
      {"number"=>27, "verses"=>26},
      {"number"=>28, "verses"=>68},
      {"number"=>29, "verses"=>29},
      {"number"=>30, "verses"=>20},
      {"number"=>31, "verses"=>30},
      {"number"=>32, "verses"=>52},
      {"number"=>33, "verses"=>29},
      {"number"=>34, "verses"=>12}]},
  {"number"=>6,
    "abbr"=>"JOS",
    "name"=>"Joshua",
    "string_id"=>"joshua",
    "chapters"=>
    [{"number"=>1, "verses"=>18},
      {"number"=>2, "verses"=>24},
      {"number"=>3, "verses"=>17},
      {"number"=>4, "verses"=>24},
      {"number"=>5, "verses"=>15},
      {"number"=>6, "verses"=>27},
      {"number"=>7, "verses"=>26},
      {"number"=>8, "verses"=>35},
      {"number"=>9, "verses"=>27},
      {"number"=>10, "verses"=>43},
      {"number"=>11, "verses"=>23},
      {"number"=>12, "verses"=>24},
      {"number"=>13, "verses"=>33},
      {"number"=>14, "verses"=>15},
      {"number"=>15, "verses"=>63},
      {"number"=>16, "verses"=>10},
      {"number"=>17, "verses"=>18},
      {"number"=>18, "verses"=>28},
      {"number"=>19, "verses"=>51},
      {"number"=>20, "verses"=>9},
      {"number"=>21, "verses"=>45},
      {"number"=>22, "verses"=>34},
      {"number"=>23, "verses"=>16},
      {"number"=>24, "verses"=>33}]},
  {"number"=>7,
    "abbr"=>"JDG",
    "name"=>"Judges",
    "string_id"=>"judges",
    "chapters"=>
    [{"number"=>1, "verses"=>36},
      {"number"=>2, "verses"=>23},
      {"number"=>3, "verses"=>31},
      {"number"=>4, "verses"=>24},
      {"number"=>5, "verses"=>31},
      {"number"=>6, "verses"=>40},
      {"number"=>7, "verses"=>25},
      {"number"=>8, "verses"=>35},
      {"number"=>9, "verses"=>57},
      {"number"=>10, "verses"=>18},
      {"number"=>11, "verses"=>40},
      {"number"=>12, "verses"=>15},
      {"number"=>13, "verses"=>25},
      {"number"=>14, "verses"=>20},
      {"number"=>15, "verses"=>20},
      {"number"=>16, "verses"=>31},
      {"number"=>17, "verses"=>13},
      {"number"=>18, "verses"=>31},
      {"number"=>19, "verses"=>30},
      {"number"=>20, "verses"=>48},
      {"number"=>21, "verses"=>25}]},
  {"number"=>8,
    "abbr"=>"RUT",
    "name"=>"Ruth",
    "string_id"=>"ruth",
    "chapters"=>
    [{"number"=>1, "verses"=>22},
      {"number"=>2, "verses"=>23},
      {"number"=>3, "verses"=>18},
      {"number"=>4, "verses"=>22}]},
  {"number"=>9,
    "abbr"=>"1SA",
    "name"=>"1 Samuel",
    "string_id"=>"1-samuel",
    "chapters"=>
    [{"number"=>1, "verses"=>28},
      {"number"=>2, "verses"=>36},
      {"number"=>3, "verses"=>21},
      {"number"=>4, "verses"=>22},
      {"number"=>5, "verses"=>12},
      {"number"=>6, "verses"=>21},
      {"number"=>7, "verses"=>17},
      {"number"=>8, "verses"=>22},
      {"number"=>9, "verses"=>27},
      {"number"=>10, "verses"=>27},
      {"number"=>11, "verses"=>15},
      {"number"=>12, "verses"=>25},
      {"number"=>13, "verses"=>23},
      {"number"=>14, "verses"=>52},
      {"number"=>15, "verses"=>35},
      {"number"=>16, "verses"=>23},
      {"number"=>17, "verses"=>58},
      {"number"=>18, "verses"=>30},
      {"number"=>19, "verses"=>24},
      {"number"=>20, "verses"=>42},
      {"number"=>21, "verses"=>15},
      {"number"=>22, "verses"=>23},
      {"number"=>23, "verses"=>29},
      {"number"=>24, "verses"=>22},
      {"number"=>25, "verses"=>44},
      {"number"=>26, "verses"=>25},
      {"number"=>27, "verses"=>12},
      {"number"=>28, "verses"=>25},
      {"number"=>29, "verses"=>11},
      {"number"=>30, "verses"=>31},
      {"number"=>31, "verses"=>13}]},
  {"number"=>10,
    "abbr"=>"2SA",
    "name"=>"2 Samuel",
    "string_id"=>"2-samuel",
    "chapters"=>
    [{"number"=>1, "verses"=>27},
      {"number"=>2, "verses"=>32},
      {"number"=>3, "verses"=>39},
      {"number"=>4, "verses"=>12},
      {"number"=>5, "verses"=>25},
      {"number"=>6, "verses"=>23},
      {"number"=>7, "verses"=>29},
      {"number"=>8, "verses"=>18},
      {"number"=>9, "verses"=>13},
      {"number"=>10, "verses"=>19},
      {"number"=>11, "verses"=>27},
      {"number"=>12, "verses"=>31},
      {"number"=>13, "verses"=>39},
      {"number"=>14, "verses"=>33},
      {"number"=>15, "verses"=>37},
      {"number"=>16, "verses"=>23},
      {"number"=>17, "verses"=>29},
      {"number"=>18, "verses"=>33},
      {"number"=>19, "verses"=>43},
      {"number"=>20, "verses"=>26},
      {"number"=>21, "verses"=>22},
      {"number"=>22, "verses"=>51},
      {"number"=>23, "verses"=>39},
      {"number"=>24, "verses"=>25}]},
  {"number"=>11,
    "abbr"=>"1KG",
    "name"=>"1 Kings",
    "string_id"=>"1-kings",
    "chapters"=>
    [{"number"=>1, "verses"=>53},
      {"number"=>2, "verses"=>46},
      {"number"=>3, "verses"=>28},
      {"number"=>4, "verses"=>34},
      {"number"=>5, "verses"=>18},
      {"number"=>6, "verses"=>38},
      {"number"=>7, "verses"=>51},
      {"number"=>8, "verses"=>66},
      {"number"=>9, "verses"=>28},
      {"number"=>10, "verses"=>29},
      {"number"=>11, "verses"=>43},
      {"number"=>12, "verses"=>33},
      {"number"=>13, "verses"=>34},
      {"number"=>14, "verses"=>31},
      {"number"=>15, "verses"=>34},
      {"number"=>16, "verses"=>34},
      {"number"=>17, "verses"=>24},
      {"number"=>18, "verses"=>46},
      {"number"=>19, "verses"=>21},
      {"number"=>20, "verses"=>43},
      {"number"=>21, "verses"=>29},
      {"number"=>22, "verses"=>53}]},
  {"number"=>12,
    "abbr"=>"2KG",
    "name"=>"2 Kings",
    "string_id"=>"2-kings",
    "chapters"=>
    [{"number"=>1, "verses"=>18},
      {"number"=>2, "verses"=>25},
      {"number"=>3, "verses"=>27},
      {"number"=>4, "verses"=>44},
      {"number"=>5, "verses"=>27},
      {"number"=>6, "verses"=>33},
      {"number"=>7, "verses"=>20},
      {"number"=>8, "verses"=>29},
      {"number"=>9, "verses"=>37},
      {"number"=>10, "verses"=>36},
      {"number"=>11, "verses"=>21},
      {"number"=>12, "verses"=>21},
      {"number"=>13, "verses"=>25},
      {"number"=>14, "verses"=>29},
      {"number"=>15, "verses"=>38},
      {"number"=>16, "verses"=>20},
      {"number"=>17, "verses"=>41},
      {"number"=>18, "verses"=>37},
      {"number"=>19, "verses"=>37},
      {"number"=>20, "verses"=>21},
      {"number"=>21, "verses"=>26},
      {"number"=>22, "verses"=>20},
      {"number"=>23, "verses"=>37},
      {"number"=>24, "verses"=>20},
      {"number"=>25, "verses"=>30}]},
  {"number"=>13,
    "abbr"=>"1KR",
    "name"=>"1 Chronicles",
    "string_id"=>"1-chronicles",
    "chapters"=>
    [{"number"=>1, "verses"=>54},
      {"number"=>2, "verses"=>55},
      {"number"=>3, "verses"=>24},
      {"number"=>4, "verses"=>43},
      {"number"=>5, "verses"=>26},
      {"number"=>6, "verses"=>81},
      {"number"=>7, "verses"=>40},
      {"number"=>8, "verses"=>40},
      {"number"=>9, "verses"=>44},
      {"number"=>10, "verses"=>14},
      {"number"=>11, "verses"=>47},
      {"number"=>12, "verses"=>40},
      {"number"=>13, "verses"=>14},
      {"number"=>14, "verses"=>17},
      {"number"=>15, "verses"=>29},
      {"number"=>16, "verses"=>43},
      {"number"=>17, "verses"=>27},
      {"number"=>18, "verses"=>17},
      {"number"=>19, "verses"=>19},
      {"number"=>20, "verses"=>8},
      {"number"=>21, "verses"=>30},
      {"number"=>22, "verses"=>19},
      {"number"=>23, "verses"=>32},
      {"number"=>24, "verses"=>31},
      {"number"=>25, "verses"=>31},
      {"number"=>26, "verses"=>32},
      {"number"=>27, "verses"=>34},
      {"number"=>28, "verses"=>21},
      {"number"=>29, "verses"=>30}]},
  {"number"=>14,
    "abbr"=>"2KR",
    "name"=>"2 Chronicles",
    "string_id"=>"2-chronicles",
    "chapters"=>
    [{"number"=>1, "verses"=>17},
      {"number"=>2, "verses"=>18},
      {"number"=>3, "verses"=>17},
      {"number"=>4, "verses"=>22},
      {"number"=>5, "verses"=>14},
      {"number"=>6, "verses"=>42},
      {"number"=>7, "verses"=>22},
      {"number"=>8, "verses"=>18},
      {"number"=>9, "verses"=>31},
      {"number"=>10, "verses"=>19},
      {"number"=>11, "verses"=>23},
      {"number"=>12, "verses"=>16},
      {"number"=>13, "verses"=>22},
      {"number"=>14, "verses"=>15},
      {"number"=>15, "verses"=>19},
      {"number"=>16, "verses"=>14},
      {"number"=>17, "verses"=>19},
      {"number"=>18, "verses"=>34},
      {"number"=>19, "verses"=>11},
      {"number"=>20, "verses"=>37},
      {"number"=>21, "verses"=>20},
      {"number"=>22, "verses"=>12},
      {"number"=>23, "verses"=>21},
      {"number"=>24, "verses"=>27},
      {"number"=>25, "verses"=>28},
      {"number"=>26, "verses"=>23},
      {"number"=>27, "verses"=>9},
      {"number"=>28, "verses"=>27},
      {"number"=>29, "verses"=>36},
      {"number"=>30, "verses"=>27},
      {"number"=>31, "verses"=>21},
      {"number"=>32, "verses"=>33},
      {"number"=>33, "verses"=>25},
      {"number"=>34, "verses"=>33},
      {"number"=>35, "verses"=>27},
      {"number"=>36, "verses"=>23}]},
  {"number"=>15,
    "abbr"=>"EZR",
    "name"=>"Ezra",
    "string_id"=>"ezra",
    "chapters"=>
    [{"number"=>1, "verses"=>11},
      {"number"=>2, "verses"=>70},
      {"number"=>3, "verses"=>13},
      {"number"=>4, "verses"=>24},
      {"number"=>5, "verses"=>17},
      {"number"=>6, "verses"=>22},
      {"number"=>7, "verses"=>28},
      {"number"=>8, "verses"=>36},
      {"number"=>9, "verses"=>15},
      {"number"=>10, "verses"=>44}]},
  {"number"=>16,
    "abbr"=>"NEH",
    "name"=>"Nehemiah",
    "string_id"=>"nehemiah",
    "chapters"=>
    [{"number"=>1, "verses"=>11},
      {"number"=>2, "verses"=>20},
      {"number"=>3, "verses"=>32},
      {"number"=>4, "verses"=>23},
      {"number"=>5, "verses"=>19},
      {"number"=>6, "verses"=>19},
      {"number"=>7, "verses"=>73},
      {"number"=>8, "verses"=>18},
      {"number"=>9, "verses"=>38},
      {"number"=>10, "verses"=>39},
      {"number"=>11, "verses"=>36},
      {"number"=>12, "verses"=>47},
      {"number"=>13, "verses"=>31}]},
  {"number"=>17,
    "abbr"=>"EST",
    "name"=>"Esther",
    "string_id"=>"esther",
    "chapters"=>
    [{"number"=>1, "verses"=>22},
      {"number"=>2, "verses"=>23},
      {"number"=>3, "verses"=>15},
      {"number"=>4, "verses"=>17},
      {"number"=>5, "verses"=>14},
      {"number"=>6, "verses"=>14},
      {"number"=>7, "verses"=>10},
      {"number"=>8, "verses"=>17},
      {"number"=>9, "verses"=>32},
      {"number"=>10, "verses"=>3}]},
  {"number"=>18,
    "abbr"=>"JOB",
    "name"=>"Job",
    "string_id"=>"job",
    "chapters"=>
    [{"number"=>1, "verses"=>22},
      {"number"=>2, "verses"=>13},
      {"number"=>3, "verses"=>26},
      {"number"=>4, "verses"=>21},
      {"number"=>5, "verses"=>27},
      {"number"=>6, "verses"=>30},
      {"number"=>7, "verses"=>21},
      {"number"=>8, "verses"=>22},
      {"number"=>9, "verses"=>35},
      {"number"=>10, "verses"=>22},
      {"number"=>11, "verses"=>20},
      {"number"=>12, "verses"=>25},
      {"number"=>13, "verses"=>28},
      {"number"=>14, "verses"=>22},
      {"number"=>15, "verses"=>35},
      {"number"=>16, "verses"=>22},
      {"number"=>17, "verses"=>16},
      {"number"=>18, "verses"=>21},
      {"number"=>19, "verses"=>29},
      {"number"=>20, "verses"=>29},
      {"number"=>21, "verses"=>34},
      {"number"=>22, "verses"=>30},
      {"number"=>23, "verses"=>17},
      {"number"=>24, "verses"=>25},
      {"number"=>25, "verses"=>6},
      {"number"=>26, "verses"=>14},
      {"number"=>27, "verses"=>23},
      {"number"=>28, "verses"=>28},
      {"number"=>29, "verses"=>25},
      {"number"=>30, "verses"=>31},
      {"number"=>31, "verses"=>40},
      {"number"=>32, "verses"=>22},
      {"number"=>33, "verses"=>33},
      {"number"=>34, "verses"=>37},
      {"number"=>35, "verses"=>16},
      {"number"=>36, "verses"=>33},
      {"number"=>37, "verses"=>24},
      {"number"=>38, "verses"=>41},
      {"number"=>39, "verses"=>30},
      {"number"=>40, "verses"=>24},
      {"number"=>41, "verses"=>34},
      {"number"=>42, "verses"=>17}]},
  {"number"=>19,
    "abbr"=>"PSA",
    "name"=>"Psalms",
    "string_id"=>"psalms",
    "chapters"=>
    [{"number"=>1, "verses"=>6},
      {"number"=>2, "verses"=>12},
      {"number"=>3, "verses"=>8},
      {"number"=>4, "verses"=>8},
      {"number"=>5, "verses"=>12},
      {"number"=>6, "verses"=>10},
      {"number"=>7, "verses"=>17},
      {"number"=>8, "verses"=>9},
      {"number"=>9, "verses"=>20},
      {"number"=>10, "verses"=>18},
      {"number"=>11, "verses"=>7},
      {"number"=>12, "verses"=>8},
      {"number"=>13, "verses"=>6},
      {"number"=>14, "verses"=>7},
      {"number"=>15, "verses"=>5},
      {"number"=>16, "verses"=>11},
      {"number"=>17, "verses"=>15},
      {"number"=>18, "verses"=>50},
      {"number"=>19, "verses"=>14},
      {"number"=>20, "verses"=>9},
      {"number"=>21, "verses"=>13},
      {"number"=>22, "verses"=>31},
      {"number"=>23, "verses"=>6},
      {"number"=>24, "verses"=>10},
      {"number"=>25, "verses"=>22},
      {"number"=>26, "verses"=>12},
      {"number"=>27, "verses"=>14},
      {"number"=>28, "verses"=>9},
      {"number"=>29, "verses"=>11},
      {"number"=>30, "verses"=>12},
      {"number"=>31, "verses"=>24},
      {"number"=>32, "verses"=>11},
      {"number"=>33, "verses"=>22},
      {"number"=>34, "verses"=>22},
      {"number"=>35, "verses"=>28},
      {"number"=>36, "verses"=>12},
      {"number"=>37, "verses"=>40},
      {"number"=>38, "verses"=>22},
      {"number"=>39, "verses"=>13},
      {"number"=>40, "verses"=>17},
      {"number"=>41, "verses"=>13},
      {"number"=>42, "verses"=>11},
      {"number"=>43, "verses"=>5},
      {"number"=>44, "verses"=>26},
      {"number"=>45, "verses"=>17},
      {"number"=>46, "verses"=>11},
      {"number"=>47, "verses"=>9},
      {"number"=>48, "verses"=>14},
      {"number"=>49, "verses"=>20},
      {"number"=>50, "verses"=>23},
      {"number"=>51, "verses"=>19},
      {"number"=>52, "verses"=>9},
      {"number"=>53, "verses"=>6},
      {"number"=>54, "verses"=>7},
      {"number"=>55, "verses"=>23},
      {"number"=>56, "verses"=>13},
      {"number"=>57, "verses"=>11},
      {"number"=>58, "verses"=>11},
      {"number"=>59, "verses"=>17},
      {"number"=>60, "verses"=>12},
      {"number"=>61, "verses"=>8},
      {"number"=>62, "verses"=>12},
      {"number"=>63, "verses"=>11},
      {"number"=>64, "verses"=>10},
      {"number"=>65, "verses"=>13},
      {"number"=>66, "verses"=>20},
      {"number"=>67, "verses"=>7},
      {"number"=>68, "verses"=>35},
      {"number"=>69, "verses"=>36},
      {"number"=>70, "verses"=>5},
      {"number"=>71, "verses"=>24},
      {"number"=>72, "verses"=>20},
      {"number"=>73, "verses"=>28},
      {"number"=>74, "verses"=>23},
      {"number"=>75, "verses"=>10},
      {"number"=>76, "verses"=>12},
      {"number"=>77, "verses"=>20},
      {"number"=>78, "verses"=>72},
      {"number"=>79, "verses"=>13},
      {"number"=>80, "verses"=>19},
      {"number"=>81, "verses"=>16},
      {"number"=>82, "verses"=>8},
      {"number"=>83, "verses"=>18},
      {"number"=>84, "verses"=>12},
      {"number"=>85, "verses"=>13},
      {"number"=>86, "verses"=>17},
      {"number"=>87, "verses"=>7},
      {"number"=>88, "verses"=>18},
      {"number"=>89, "verses"=>52},
      {"number"=>90, "verses"=>17},
      {"number"=>91, "verses"=>16},
      {"number"=>92, "verses"=>15},
      {"number"=>93, "verses"=>5},
      {"number"=>94, "verses"=>23},
      {"number"=>95, "verses"=>11},
      {"number"=>96, "verses"=>13},
      {"number"=>97, "verses"=>12},
      {"number"=>98, "verses"=>9},
      {"number"=>99, "verses"=>9},
      {"number"=>100, "verses"=>5},
      {"number"=>101, "verses"=>8},
      {"number"=>102, "verses"=>28},
      {"number"=>103, "verses"=>22},
      {"number"=>104, "verses"=>35},
      {"number"=>105, "verses"=>45},
      {"number"=>106, "verses"=>48},
      {"number"=>107, "verses"=>43},
      {"number"=>108, "verses"=>13},
      {"number"=>109, "verses"=>31},
      {"number"=>110, "verses"=>7},
      {"number"=>111, "verses"=>10},
      {"number"=>112, "verses"=>10},
      {"number"=>113, "verses"=>9},
      {"number"=>114, "verses"=>8},
      {"number"=>115, "verses"=>18},
      {"number"=>116, "verses"=>19},
      {"number"=>117, "verses"=>2},
      {"number"=>118, "verses"=>29},
      {"number"=>119, "verses"=>176},
      {"number"=>120, "verses"=>7},
      {"number"=>121, "verses"=>8},
      {"number"=>122, "verses"=>9},
      {"number"=>123, "verses"=>4},
      {"number"=>124, "verses"=>8},
      {"number"=>125, "verses"=>5},
      {"number"=>126, "verses"=>6},
      {"number"=>127, "verses"=>5},
      {"number"=>128, "verses"=>6},
      {"number"=>129, "verses"=>8},
      {"number"=>130, "verses"=>8},
      {"number"=>131, "verses"=>3},
      {"number"=>132, "verses"=>18},
      {"number"=>133, "verses"=>3},
      {"number"=>134, "verses"=>3},
      {"number"=>135, "verses"=>21},
      {"number"=>136, "verses"=>26},
      {"number"=>137, "verses"=>9},
      {"number"=>138, "verses"=>8},
      {"number"=>139, "verses"=>24},
      {"number"=>140, "verses"=>13},
      {"number"=>141, "verses"=>10},
      {"number"=>142, "verses"=>7},
      {"number"=>143, "verses"=>12},
      {"number"=>144, "verses"=>15},
      {"number"=>145, "verses"=>21},
      {"number"=>146, "verses"=>10},
      {"number"=>147, "verses"=>20},
      {"number"=>148, "verses"=>14},
      {"number"=>149, "verses"=>9},
      {"number"=>150, "verses"=>6}]},
  {"number"=>20,
    "abbr"=>"PRO",
    "name"=>"Proverbs",
    "string_id"=>"proverbs",
    "chapters"=>
    [{"number"=>1, "verses"=>33},
      {"number"=>2, "verses"=>22},
      {"number"=>3, "verses"=>35},
      {"number"=>4, "verses"=>27},
      {"number"=>5, "verses"=>23},
      {"number"=>6, "verses"=>35},
      {"number"=>7, "verses"=>27},
      {"number"=>8, "verses"=>36},
      {"number"=>9, "verses"=>18},
      {"number"=>10, "verses"=>32},
      {"number"=>11, "verses"=>31},
      {"number"=>12, "verses"=>28},
      {"number"=>13, "verses"=>25},
      {"number"=>14, "verses"=>35},
      {"number"=>15, "verses"=>33},
      {"number"=>16, "verses"=>33},
      {"number"=>17, "verses"=>28},
      {"number"=>18, "verses"=>24},
      {"number"=>19, "verses"=>29},
      {"number"=>20, "verses"=>30},
      {"number"=>21, "verses"=>31},
      {"number"=>22, "verses"=>29},
      {"number"=>23, "verses"=>35},
      {"number"=>24, "verses"=>34},
      {"number"=>25, "verses"=>28},
      {"number"=>26, "verses"=>28},
      {"number"=>27, "verses"=>27},
      {"number"=>28, "verses"=>28},
      {"number"=>29, "verses"=>27},
      {"number"=>30, "verses"=>33},
      {"number"=>31, "verses"=>31}]},
  {"number"=>21,
    "abbr"=>"ECC",
    "name"=>"Ecclesiastes",
    "string_id"=>"ecclesiastes",
    "chapters"=>
    [{"number"=>1, "verses"=>18},
      {"number"=>2, "verses"=>26},
      {"number"=>3, "verses"=>22},
      {"number"=>4, "verses"=>16},
      {"number"=>5, "verses"=>20},
      {"number"=>6, "verses"=>12},
      {"number"=>7, "verses"=>29},
      {"number"=>8, "verses"=>17},
      {"number"=>9, "verses"=>18},
      {"number"=>10, "verses"=>20},
      {"number"=>11, "verses"=>10},
      {"number"=>12, "verses"=>14}]},
  {"number"=>22,
    "abbr"=>"SO",
    "name"=>"Song of Solomon",
    "string_id"=>"song-of-solomon",
    "chapters"=>
    [{"number"=>1, "verses"=>17},
      {"number"=>2, "verses"=>17},
      {"number"=>3, "verses"=>11},
      {"number"=>4, "verses"=>16},
      {"number"=>5, "verses"=>16},
      {"number"=>6, "verses"=>13},
      {"number"=>7, "verses"=>13},
      {"number"=>8, "verses"=>14}]},
  {"number"=>23,
    "abbr"=>"ISA",
    "name"=>"Isaiah",
    "string_id"=>"isaiah",
    "chapters"=>
    [{"number"=>1, "verses"=>31},
      {"number"=>2, "verses"=>22},
      {"number"=>3, "verses"=>26},
      {"number"=>4, "verses"=>6},
      {"number"=>5, "verses"=>30},
      {"number"=>6, "verses"=>13},
      {"number"=>7, "verses"=>25},
      {"number"=>8, "verses"=>22},
      {"number"=>9, "verses"=>21},
      {"number"=>10, "verses"=>34},
      {"number"=>11, "verses"=>16},
      {"number"=>12, "verses"=>6},
      {"number"=>13, "verses"=>22},
      {"number"=>14, "verses"=>32},
      {"number"=>15, "verses"=>9},
      {"number"=>16, "verses"=>14},
      {"number"=>17, "verses"=>14},
      {"number"=>18, "verses"=>7},
      {"number"=>19, "verses"=>25},
      {"number"=>20, "verses"=>6},
      {"number"=>21, "verses"=>17},
      {"number"=>22, "verses"=>25},
      {"number"=>23, "verses"=>18},
      {"number"=>24, "verses"=>23},
      {"number"=>25, "verses"=>12},
      {"number"=>26, "verses"=>21},
      {"number"=>27, "verses"=>13},
      {"number"=>28, "verses"=>29},
      {"number"=>29, "verses"=>24},
      {"number"=>30, "verses"=>33},
      {"number"=>31, "verses"=>9},
      {"number"=>32, "verses"=>20},
      {"number"=>33, "verses"=>24},
      {"number"=>34, "verses"=>17},
      {"number"=>35, "verses"=>10},
      {"number"=>36, "verses"=>22},
      {"number"=>37, "verses"=>38},
      {"number"=>38, "verses"=>22},
      {"number"=>39, "verses"=>8},
      {"number"=>40, "verses"=>31},
      {"number"=>41, "verses"=>29},
      {"number"=>42, "verses"=>25},
      {"number"=>43, "verses"=>28},
      {"number"=>44, "verses"=>28},
      {"number"=>45, "verses"=>25},
      {"number"=>46, "verses"=>13},
      {"number"=>47, "verses"=>15},
      {"number"=>48, "verses"=>22},
      {"number"=>49, "verses"=>26},
      {"number"=>50, "verses"=>11},
      {"number"=>51, "verses"=>23},
      {"number"=>52, "verses"=>15},
      {"number"=>53, "verses"=>12},
      {"number"=>54, "verses"=>17},
      {"number"=>55, "verses"=>13},
      {"number"=>56, "verses"=>12},
      {"number"=>57, "verses"=>21},
      {"number"=>58, "verses"=>14},
      {"number"=>59, "verses"=>21},
      {"number"=>60, "verses"=>22},
      {"number"=>61, "verses"=>11},
      {"number"=>62, "verses"=>12},
      {"number"=>63, "verses"=>19},
      {"number"=>64, "verses"=>12},
      {"number"=>65, "verses"=>25},
      {"number"=>66, "verses"=>24}]},
  {"number"=>24,
    "abbr"=>"JER",
    "name"=>"Jeremiah",
    "string_id"=>"jeremiah",
    "chapters"=>
    [{"number"=>1, "verses"=>19},
      {"number"=>2, "verses"=>37},
      {"number"=>3, "verses"=>25},
      {"number"=>4, "verses"=>31},
      {"number"=>5, "verses"=>31},
      {"number"=>6, "verses"=>30},
      {"number"=>7, "verses"=>34},
      {"number"=>8, "verses"=>22},
      {"number"=>9, "verses"=>26},
      {"number"=>10, "verses"=>25},
      {"number"=>11, "verses"=>23},
      {"number"=>12, "verses"=>17},
      {"number"=>13, "verses"=>27},
      {"number"=>14, "verses"=>22},
      {"number"=>15, "verses"=>21},
      {"number"=>16, "verses"=>21},
      {"number"=>17, "verses"=>27},
      {"number"=>18, "verses"=>23},
      {"number"=>19, "verses"=>15},
      {"number"=>20, "verses"=>18},
      {"number"=>21, "verses"=>14},
      {"number"=>22, "verses"=>30},
      {"number"=>23, "verses"=>40},
      {"number"=>24, "verses"=>10},
      {"number"=>25, "verses"=>38},
      {"number"=>26, "verses"=>24},
      {"number"=>27, "verses"=>22},
      {"number"=>28, "verses"=>17},
      {"number"=>29, "verses"=>32},
      {"number"=>30, "verses"=>24},
      {"number"=>31, "verses"=>40},
      {"number"=>32, "verses"=>44},
      {"number"=>33, "verses"=>26},
      {"number"=>34, "verses"=>22},
      {"number"=>35, "verses"=>19},
      {"number"=>36, "verses"=>32},
      {"number"=>37, "verses"=>21},
      {"number"=>38, "verses"=>28},
      {"number"=>39, "verses"=>18},
      {"number"=>40, "verses"=>16},
      {"number"=>41, "verses"=>18},
      {"number"=>42, "verses"=>22},
      {"number"=>43, "verses"=>13},
      {"number"=>44, "verses"=>30},
      {"number"=>45, "verses"=>5},
      {"number"=>46, "verses"=>28},
      {"number"=>47, "verses"=>7},
      {"number"=>48, "verses"=>47},
      {"number"=>49, "verses"=>39},
      {"number"=>50, "verses"=>46},
      {"number"=>51, "verses"=>64},
      {"number"=>52, "verses"=>34}]},
  {"number"=>25,
    "abbr"=>"LAM",
    "name"=>"Lamentations",
    "string_id"=>"lamentations",
    "chapters"=>
    [{"number"=>1, "verses"=>22},
      {"number"=>2, "verses"=>22},
      {"number"=>3, "verses"=>66},
      {"number"=>4, "verses"=>22},
      {"number"=>5, "verses"=>22}]},
  {"number"=>26,
    "abbr"=>"EZE",
    "name"=>"Ezekiel",
    "string_id"=>"ezekiel",
    "chapters"=>
    [{"number"=>1, "verses"=>28},
      {"number"=>2, "verses"=>10},
      {"number"=>3, "verses"=>27},
      {"number"=>4, "verses"=>17},
      {"number"=>5, "verses"=>17},
      {"number"=>6, "verses"=>14},
      {"number"=>7, "verses"=>27},
      {"number"=>8, "verses"=>18},
      {"number"=>9, "verses"=>11},
      {"number"=>10, "verses"=>22},
      {"number"=>11, "verses"=>25},
      {"number"=>12, "verses"=>28},
      {"number"=>13, "verses"=>23},
      {"number"=>14, "verses"=>23},
      {"number"=>15, "verses"=>8},
      {"number"=>16, "verses"=>63},
      {"number"=>17, "verses"=>24},
      {"number"=>18, "verses"=>32},
      {"number"=>19, "verses"=>14},
      {"number"=>20, "verses"=>49},
      {"number"=>21, "verses"=>32},
      {"number"=>22, "verses"=>31},
      {"number"=>23, "verses"=>49},
      {"number"=>24, "verses"=>27},
      {"number"=>25, "verses"=>17},
      {"number"=>26, "verses"=>21},
      {"number"=>27, "verses"=>36},
      {"number"=>28, "verses"=>26},
      {"number"=>29, "verses"=>21},
      {"number"=>30, "verses"=>26},
      {"number"=>31, "verses"=>18},
      {"number"=>32, "verses"=>32},
      {"number"=>33, "verses"=>33},
      {"number"=>34, "verses"=>31},
      {"number"=>35, "verses"=>15},
      {"number"=>36, "verses"=>38},
      {"number"=>37, "verses"=>28},
      {"number"=>38, "verses"=>23},
      {"number"=>39, "verses"=>29},
      {"number"=>40, "verses"=>49},
      {"number"=>41, "verses"=>26},
      {"number"=>42, "verses"=>20},
      {"number"=>43, "verses"=>27},
      {"number"=>44, "verses"=>31},
      {"number"=>45, "verses"=>25},
      {"number"=>46, "verses"=>24},
      {"number"=>47, "verses"=>23},
      {"number"=>48, "verses"=>35}]},
  {"number"=>27,
    "abbr"=>"DAN",
    "name"=>"Daniel",
    "string_id"=>"daniel",
    "chapters"=>
    [{"number"=>1, "verses"=>21},
      {"number"=>2, "verses"=>49},
      {"number"=>3, "verses"=>30},
      {"number"=>4, "verses"=>37},
      {"number"=>5, "verses"=>31},
      {"number"=>6, "verses"=>28},
      {"number"=>7, "verses"=>28},
      {"number"=>8, "verses"=>27},
      {"number"=>9, "verses"=>27},
      {"number"=>10, "verses"=>21},
      {"number"=>11, "verses"=>45},
      {"number"=>12, "verses"=>13}]},
  {"number"=>28,
    "abbr"=>"HOS",
    "name"=>"Hosea",
    "string_id"=>"hosea",
    "chapters"=>
    [{"number"=>1, "verses"=>11},
      {"number"=>2, "verses"=>23},
      {"number"=>3, "verses"=>5},
      {"number"=>4, "verses"=>19},
      {"number"=>5, "verses"=>15},
      {"number"=>6, "verses"=>11},
      {"number"=>7, "verses"=>16},
      {"number"=>8, "verses"=>14},
      {"number"=>9, "verses"=>17},
      {"number"=>10, "verses"=>15},
      {"number"=>11, "verses"=>12},
      {"number"=>12, "verses"=>14},
      {"number"=>13, "verses"=>16},
      {"number"=>14, "verses"=>9}]},
  {"number"=>29,
    "abbr"=>"JOE",
    "name"=>"Joel",
    "string_id"=>"joel",
    "chapters"=>
    [{"number"=>1, "verses"=>20},
      {"number"=>2, "verses"=>32},
      {"number"=>3, "verses"=>21}]},
  {"number"=>30,
    "abbr"=>"AMO",
    "name"=>"Amos",
    "string_id"=>"amos",
    "chapters"=>
    [{"number"=>1, "verses"=>15},
      {"number"=>2, "verses"=>16},
      {"number"=>3, "verses"=>15},
      {"number"=>4, "verses"=>13},
      {"number"=>5, "verses"=>27},
      {"number"=>6, "verses"=>14},
      {"number"=>7, "verses"=>17},
      {"number"=>8, "verses"=>14},
      {"number"=>9, "verses"=>15}]},
  {"number"=>31,
    "abbr"=>"OBA",
    "name"=>"Obadiah",
    "string_id"=>"obadiah",
    "chapters"=>[{"number"=>1, "verses"=>21}]},
  {"number"=>32,
    "abbr"=>"JON",
    "name"=>"Jonah",
    "string_id"=>"jonah",
    "chapters"=>
    [{"number"=>1, "verses"=>17},
      {"number"=>2, "verses"=>10},
      {"number"=>3, "verses"=>10},
      {"number"=>4, "verses"=>11}]},
  {"number"=>33,
    "abbr"=>"MIC",
    "name"=>"Micah",
    "string_id"=>"micah",
    "chapters"=>
    [{"number"=>1, "verses"=>16},
      {"number"=>2, "verses"=>13},
      {"number"=>3, "verses"=>12},
      {"number"=>4, "verses"=>13},
      {"number"=>5, "verses"=>15},
      {"number"=>6, "verses"=>16},
      {"number"=>7, "verses"=>20}]},
  {"number"=>34,
    "abbr"=>"NAH",
    "name"=>"Nahum",
    "string_id"=>"nahum",
    "chapters"=>
    [{"number"=>1, "verses"=>15},
      {"number"=>2, "verses"=>13},
      {"number"=>3, "verses"=>19}]},
  {"number"=>35,
    "abbr"=>"HAB",
    "name"=>"Habakkuk",
    "string_id"=>"habakkuk",
    "chapters"=>
    [{"number"=>1, "verses"=>17},
      {"number"=>2, "verses"=>20},
      {"number"=>3, "verses"=>19}]},
  {"number"=>36,
    "abbr"=>"ZEP",
    "name"=>"Zephaniah",
    "string_id"=>"zephaniah",
    "chapters"=>
    [{"number"=>1, "verses"=>18},
      {"number"=>2, "verses"=>15},
      {"number"=>3, "verses"=>20}]},
  {"number"=>37,
    "abbr"=>"HAG",
    "name"=>"Haggai",
    "string_id"=>"haggai",
    "chapters"=>[{"number"=>1, "verses"=>15}, {"number"=>2, "verses"=>23}]},
  {"number"=>38,
    "abbr"=>"ZEC",
    "name"=>"Zechariah",
    "string_id"=>"zechariah",
    "chapters"=>
    [{"number"=>1, "verses"=>21},
      {"number"=>2, "verses"=>13},
      {"number"=>3, "verses"=>10},
      {"number"=>4, "verses"=>14},
      {"number"=>5, "verses"=>11},
      {"number"=>6, "verses"=>15},
      {"number"=>7, "verses"=>14},
      {"number"=>8, "verses"=>23},
      {"number"=>9, "verses"=>17},
      {"number"=>10, "verses"=>12},
      {"number"=>11, "verses"=>17},
      {"number"=>12, "verses"=>14},
      {"number"=>13, "verses"=>9},
      {"number"=>14, "verses"=>21}]},
  {"number"=>39,
    "abbr"=>"MAL",
    "name"=>"Malachi",
    "string_id"=>"malachi",
    "chapters"=>
    [{"number"=>1, "verses"=>14},
      {"number"=>2, "verses"=>17},
      {"number"=>3, "verses"=>18},
      {"number"=>4, "verses"=>6}]},
  {"number"=>40,
    "abbr"=>"MAT",
    "name"=>"Matthew",
    "string_id"=>"matthew",
    "chapters"=>
    [{"number"=>1, "verses"=>25},
      {"number"=>2, "verses"=>23},
      {"number"=>3, "verses"=>17},
      {"number"=>4, "verses"=>25},
      {"number"=>5, "verses"=>48},
      {"number"=>6, "verses"=>34},
      {"number"=>7, "verses"=>29},
      {"number"=>8, "verses"=>34},
      {"number"=>9, "verses"=>38},
      {"number"=>10, "verses"=>42},
      {"number"=>11, "verses"=>30},
      {"number"=>12, "verses"=>49},
      {"number"=>13, "verses"=>58},
      {"number"=>14, "verses"=>36},
      {"number"=>15, "verses"=>39},
      {"number"=>16, "verses"=>28},
      {"number"=>17, "verses"=>26},
      {"number"=>18, "verses"=>34},
      {"number"=>19, "verses"=>30},
      {"number"=>20, "verses"=>34},
      {"number"=>21, "verses"=>46},
      {"number"=>22, "verses"=>46},
      {"number"=>23, "verses"=>38},
      {"number"=>24, "verses"=>51},
      {"number"=>25, "verses"=>46},
      {"number"=>26, "verses"=>75},
      {"number"=>27, "verses"=>66},
      {"number"=>28, "verses"=>20}]},
  {"number"=>41,
    "abbr"=>"MAR",
    "name"=>"Mark",
    "string_id"=>"mark",
    "chapters"=>
    [{"number"=>1, "verses"=>45},
      {"number"=>2, "verses"=>28},
      {"number"=>3, "verses"=>35},
      {"number"=>4, "verses"=>41},
      {"number"=>5, "verses"=>43},
      {"number"=>6, "verses"=>56},
      {"number"=>7, "verses"=>36},
      {"number"=>8, "verses"=>38},
      {"number"=>9, "verses"=>48},
      {"number"=>10, "verses"=>52},
      {"number"=>11, "verses"=>32},
      {"number"=>12, "verses"=>44},
      {"number"=>13, "verses"=>37},
      {"number"=>14, "verses"=>72},
      {"number"=>15, "verses"=>46},
      {"number"=>16, "verses"=>20}]},
  {"number"=>42,
    "abbr"=>"LUK",
    "name"=>"Luke",
    "string_id"=>"luke",
    "chapters"=>
    [{"number"=>1, "verses"=>80},
      {"number"=>2, "verses"=>52},
      {"number"=>3, "verses"=>38},
      {"number"=>4, "verses"=>44},
      {"number"=>5, "verses"=>39},
      {"number"=>6, "verses"=>49},
      {"number"=>7, "verses"=>50},
      {"number"=>8, "verses"=>56},
      {"number"=>9, "verses"=>62},
      {"number"=>10, "verses"=>42},
      {"number"=>11, "verses"=>54},
      {"number"=>12, "verses"=>59},
      {"number"=>13, "verses"=>35},
      {"number"=>14, "verses"=>35},
      {"number"=>15, "verses"=>32},
      {"number"=>16, "verses"=>31},
      {"number"=>17, "verses"=>36},
      {"number"=>18, "verses"=>43},
      {"number"=>19, "verses"=>48},
      {"number"=>20, "verses"=>47},
      {"number"=>21, "verses"=>38},
      {"number"=>22, "verses"=>71},
      {"number"=>23, "verses"=>55},
      {"number"=>24, "verses"=>53}]},
  {"number"=>43,
    "abbr"=>"JOH",
    "name"=>"John",
    "string_id"=>"john",
    "chapters"=>
    [{"number"=>1, "verses"=>51},
      {"number"=>2, "verses"=>25},
      {"number"=>3, "verses"=>36},
      {"number"=>4, "verses"=>54},
      {"number"=>5, "verses"=>46},
      {"number"=>6, "verses"=>71},
      {"number"=>7, "verses"=>53},
      {"number"=>8, "verses"=>59},
      {"number"=>9, "verses"=>41},
      {"number"=>10, "verses"=>42},
      {"number"=>11, "verses"=>57},
      {"number"=>12, "verses"=>50},
      {"number"=>13, "verses"=>38},
      {"number"=>14, "verses"=>31},
      {"number"=>15, "verses"=>27},
      {"number"=>16, "verses"=>33},
      {"number"=>17, "verses"=>26},
      {"number"=>18, "verses"=>40},
      {"number"=>19, "verses"=>42},
      {"number"=>20, "verses"=>31},
      {"number"=>21, "verses"=>25}]},
  {"number"=>44,
    "abbr"=>"ACT",
    "name"=>"Acts",
    "string_id"=>"acts",
    "chapters"=>
    [{"number"=>1, "verses"=>26},
      {"number"=>2, "verses"=>47},
      {"number"=>3, "verses"=>26},
      {"number"=>4, "verses"=>37},
      {"number"=>5, "verses"=>42},
      {"number"=>6, "verses"=>15},
      {"number"=>7, "verses"=>60},
      {"number"=>8, "verses"=>39},
      {"number"=>9, "verses"=>43},
      {"number"=>10, "verses"=>48},
      {"number"=>11, "verses"=>30},
      {"number"=>12, "verses"=>25},
      {"number"=>13, "verses"=>52},
      {"number"=>14, "verses"=>28},
      {"number"=>15, "verses"=>40},
      {"number"=>16, "verses"=>40},
      {"number"=>17, "verses"=>34},
      {"number"=>18, "verses"=>28},
      {"number"=>19, "verses"=>41},
      {"number"=>20, "verses"=>38},
      {"number"=>21, "verses"=>40},
      {"number"=>22, "verses"=>30},
      {"number"=>23, "verses"=>35},
      {"number"=>24, "verses"=>26},
      {"number"=>25, "verses"=>27},
      {"number"=>26, "verses"=>32},
      {"number"=>27, "verses"=>44},
      {"number"=>28, "verses"=>30}]},
  {"number"=>45,
    "abbr"=>"ROM",
    "name"=>"Romans",
    "string_id"=>"romans",
    "chapters"=>
    [{"number"=>1, "verses"=>32},
      {"number"=>2, "verses"=>29},
      {"number"=>3, "verses"=>31},
      {"number"=>4, "verses"=>25},
      {"number"=>5, "verses"=>21},
      {"number"=>6, "verses"=>23},
      {"number"=>7, "verses"=>25},
      {"number"=>8, "verses"=>39},
      {"number"=>9, "verses"=>33},
      {"number"=>10, "verses"=>21},
      {"number"=>11, "verses"=>36},
      {"number"=>12, "verses"=>21},
      {"number"=>13, "verses"=>14},
      {"number"=>14, "verses"=>23},
      {"number"=>15, "verses"=>33},
      {"number"=>16, "verses"=>26}]},
  {"number"=>46,
    "abbr"=>"1CO",
    "name"=>"1 Corinthians",
    "string_id"=>"1-corinthians",
    "chapters"=>
    [{"number"=>1, "verses"=>31},
      {"number"=>2, "verses"=>16},
      {"number"=>3, "verses"=>23},
      {"number"=>4, "verses"=>21},
      {"number"=>5, "verses"=>13},
      {"number"=>6, "verses"=>20},
      {"number"=>7, "verses"=>40},
      {"number"=>8, "verses"=>13},
      {"number"=>9, "verses"=>27},
      {"number"=>10, "verses"=>33},
      {"number"=>11, "verses"=>34},
      {"number"=>12, "verses"=>31},
      {"number"=>13, "verses"=>13},
      {"number"=>14, "verses"=>40},
      {"number"=>15, "verses"=>58},
      {"number"=>16, "verses"=>24}]},
  {"number"=>47,
    "abbr"=>"2CO",
    "name"=>"2 Corinthians",
    "string_id"=>"2-corinthians",
    "chapters"=>
    [{"number"=>1, "verses"=>24},
      {"number"=>2, "verses"=>17},
      {"number"=>3, "verses"=>18},
      {"number"=>4, "verses"=>18},
      {"number"=>5, "verses"=>21},
      {"number"=>6, "verses"=>18},
      {"number"=>7, "verses"=>16},
      {"number"=>8, "verses"=>24},
      {"number"=>9, "verses"=>15},
      {"number"=>10, "verses"=>18},
      {"number"=>11, "verses"=>33},
      {"number"=>12, "verses"=>21},
      {"number"=>13, "verses"=>14}]},
  {"number"=>48,
    "abbr"=>"GAL",
    "name"=>"Galatians",
    "string_id"=>"galatians",
    "chapters"=>
    [{"number"=>1, "verses"=>24},
      {"number"=>2, "verses"=>21},
      {"number"=>3, "verses"=>29},
      {"number"=>4, "verses"=>31},
      {"number"=>5, "verses"=>26},
      {"number"=>6, "verses"=>18}]},
  {"number"=>49,
    "abbr"=>"EPH",
    "name"=>"Ephesians",
    "string_id"=>"ephesians",
    "chapters"=>
    [{"number"=>1, "verses"=>23},
      {"number"=>2, "verses"=>22},
      {"number"=>3, "verses"=>21},
      {"number"=>4, "verses"=>32},
      {"number"=>5, "verses"=>33},
      {"number"=>6, "verses"=>24}]},
  {"number"=>50,
    "abbr"=>"PHI",
    "name"=>"Philippians",
    "string_id"=>"philippians",
    "chapters"=>
    [{"number"=>1, "verses"=>30},
      {"number"=>2, "verses"=>30},
      {"number"=>3, "verses"=>21},
      {"number"=>4, "verses"=>23}]},
  {"number"=>51,
    "abbr"=>"COL",
    "name"=>"Colossians",
    "string_id"=>"colossians",
    "chapters"=>
    [{"number"=>1, "verses"=>29},
      {"number"=>2, "verses"=>23},
      {"number"=>3, "verses"=>25},
      {"number"=>4, "verses"=>18}]},
  {"number"=>52,
    "abbr"=>"1TH",
    "name"=>"1 Thessalonians",
    "string_id"=>"1-thessalonians",
    "chapters"=>
    [{"number"=>1, "verses"=>10},
      {"number"=>2, "verses"=>20},
      {"number"=>3, "verses"=>13},
      {"number"=>4, "verses"=>18},
      {"number"=>5, "verses"=>28}]},
  {"number"=>53,
    "abbr"=>"2TH",
    "name"=>"2 Thessalonians",
    "string_id"=>"2-thessalonians",
    "chapters"=>
    [{"number"=>1, "verses"=>12},
      {"number"=>2, "verses"=>17},
      {"number"=>3, "verses"=>18}]},
  {"number"=>54,
    "abbr"=>"1TI",
    "name"=>"1 Timothy",
    "string_id"=>"1-timothy",
    "chapters"=>
    [{"number"=>1, "verses"=>20},
      {"number"=>2, "verses"=>15},
      {"number"=>3, "verses"=>16},
      {"number"=>4, "verses"=>16},
      {"number"=>5, "verses"=>25},
      {"number"=>6, "verses"=>21}]},
  {"number"=>55,
    "abbr"=>"2TI",
    "name"=>"2 Timothy",
    "string_id"=>"2-timothy",
    "chapters"=>
    [{"number"=>1, "verses"=>18},
      {"number"=>2, "verses"=>26},
      {"number"=>3, "verses"=>17},
      {"number"=>4, "verses"=>22}]},
  {"number"=>56,
    "abbr"=>"TIT",
    "name"=>"Titus",
    "string_id"=>"titus",
    "chapters"=>
    [{"number"=>1, "verses"=>16},
      {"number"=>2, "verses"=>15},
      {"number"=>3, "verses"=>15}]},
  {"number"=>57,
    "abbr"=>"PHM",
    "name"=>"Philemon",
    "string_id"=>"philemon",
    "chapters"=>[{"number"=>1, "verses"=>25}]},
  {"number"=>58,
    "abbr"=>"HEB",
    "name"=>"Hebrews",
    "string_id"=>"hebrews",
    "chapters"=>
    [{"number"=>1, "verses"=>14},
      {"number"=>2, "verses"=>18},
      {"number"=>3, "verses"=>19},
      {"number"=>4, "verses"=>16},
      {"number"=>5, "verses"=>14},
      {"number"=>6, "verses"=>20},
      {"number"=>7, "verses"=>28},
      {"number"=>8, "verses"=>13},
      {"number"=>9, "verses"=>28},
      {"number"=>10, "verses"=>39},
      {"number"=>11, "verses"=>40},
      {"number"=>12, "verses"=>29},
      {"number"=>13, "verses"=>25}]},
  {"number"=>59,
    "abbr"=>"JAM",
    "name"=>"James",
    "string_id"=>"james",
    "chapters"=>
    [{"number"=>1, "verses"=>27},
      {"number"=>2, "verses"=>26},
      {"number"=>3, "verses"=>18},
      {"number"=>4, "verses"=>17},
      {"number"=>5, "verses"=>20}]},
  {"number"=>60,
    "abbr"=>"1PE",
    "name"=>"1 Peter",
    "string_id"=>"1-peter",
    "chapters"=>
    [{"number"=>1, "verses"=>25},
      {"number"=>2, "verses"=>25},
      {"number"=>3, "verses"=>22},
      {"number"=>4, "verses"=>19},
      {"number"=>5, "verses"=>14}]},
  {"number"=>61,
    "abbr"=>"2PE",
    "name"=>"2 Peter",
    "string_id"=>"2-peter",
    "chapters"=>
    [{"number"=>1, "verses"=>21},
      {"number"=>2, "verses"=>22},
      {"number"=>3, "verses"=>18}]},
  {"number"=>62,
    "abbr"=>"1JO",
    "name"=>"1 John",
    "string_id"=>"1-john",
    "chapters"=>
    [{"number"=>1, "verses"=>10},
      {"number"=>2, "verses"=>29},
      {"number"=>3, "verses"=>24},
      {"number"=>4, "verses"=>21},
      {"number"=>5, "verses"=>21}]},
  {"number"=>63,
    "abbr"=>"2JO",
    "name"=>"2 John",
    "string_id"=>"2-john",
    "chapters"=>[{"number"=>1, "verses"=>13}]},
  {"number"=>64,
    "abbr"=>"3JO",
    "name"=>"3 John",
    "string_id"=>"3-john",
    "chapters"=>[{"number"=>1, "verses"=>15}]},
  {"number"=>65,
    "abbr"=>"JUD",
    "name"=>"Jude",
    "string_id"=>"jude",
    "chapters"=>[{"number"=>1, "verses"=>25}]},
  {"number"=>66,
    "abbr"=>"REV",
    "name"=>"Revelation",
    "string_id"=>"revelation",
    "chapters"=>
    [{"number"=>1, "verses"=>20},
      {"number"=>2, "verses"=>29},
      {"number"=>3, "verses"=>22},
      {"number"=>4, "verses"=>11},
      {"number"=>5, "verses"=>14},
      {"number"=>6, "verses"=>17},
      {"number"=>7, "verses"=>17},
      {"number"=>8, "verses"=>13},
      {"number"=>9, "verses"=>21},
      {"number"=>10, "verses"=>11},
      {"number"=>11, "verses"=>19},
      {"number"=>12, "verses"=>17},
      {"number"=>13, "verses"=>18},
      {"number"=>14, "verses"=>20},
      {"number"=>15, "verses"=>8},
      {"number"=>16, "verses"=>21},
      {"number"=>17, "verses"=>18},
      {"number"=>18, "verses"=>24},
      {"number"=>19, "verses"=>21},
      {"number"=>20, "verses"=>15},
      {"number"=>21, "verses"=>27},
      {"number"=>22, "verses"=>21}]}]
end





